#! /bin/sh

#
# Functions
#
create_directories () {
    path="${1}"

    for dir in $(find ${path} -type d | sed "s|${path}|${HOME}|"); do
        if [ ! -e ${dir} ]; then
            echo "Creating directory ${dir}"
            mkdir -p ${dir}
        fi
    done
}

create_symlinks () {
    path="${1}"

    for file in $(find ${path} -type f); do
        target=$(readlink -f "${file}")
        link=$(echo -n "${file}" | sed "s|${path}|${HOME}|")
        if [ -f "${link}" ]; then
            echo "${link} is a regular file, skipping it"
        else
            echo "Creating symlink ${link}"
            ln -sf "${target}" "${link}"
        fi
    done
}

#
# Main
#
if [ $# -ne 1 ]; then
    echo "usage: $(basename $0) dotfiles_directory"
    exit 1
fi

dotfiles_directory="$(dirname $0)/$1"
if [ ! -d "${dotfiles_directory}" ]; then
    echo "${dotfiles_directory} is not a directory"
    exit 1
fi

IFS="
"
create_directories "${dotfiles_directory}"
create_symlinks "${dotfiles_directory}"
